cd 56-day_sets
cp 'Albuquerque SEC.tif'                    ../../Programs/OpenEagleMaps/Albuquerque_Sectional/'Albuquerque SEC.tif'
cp 'Anchorage SEC.tif'                      ../../Programs/OpenEagleMaps/Anchorage_Sectional/'Anchorage SEC.tif'
cp 'Atlanta SEC.tif'                        ../../Programs/OpenEagleMaps/Atlanta_Sectional/'Atlanta SEC.tif'
cp 'Bethel SEC.tif'                         ../../Programs/OpenEagleMaps/Bethel_Sectional/'Bethel SEC.tif'
cp 'Billings SEC.tif'                       ../../Programs/OpenEagleMaps/Billings_Sectional/'Billings SEC.tif'
cp 'Brownsville SEC.tif'                    ../../Programs/OpenEagleMaps/Brownsville_Sectional/'Brownsville SEC.tif'
cp 'Cape Lisburne SEC.tif'                  ../../Programs/OpenEagleMaps/Cape_Lisburne_Sectional/'Cape Lisburne SEC.tif'
cp 'Charlotte SEC.tif'                      ../../Programs/OpenEagleMaps/Charlotte_Sectional/'Charlotte SEC.tif'
cp 'Cheyenne SEC.tif'                       ../../Programs/OpenEagleMaps/Cheyenne_Sectional/'Cheyenne SEC.tif'
cp 'Chicago SEC.tif'                        ../../Programs/OpenEagleMaps/Chicago_Sectional/'Chicago SEC.tif'
cp 'Cincinnati SEC.tif'                     ../../Programs/OpenEagleMaps/Cincinnati_Sectional/'Cincinnati SEC.tif'
cp 'Cold Bay SEC.tif'                       ../../Programs/OpenEagleMaps/Cold_Bay_Sectional/'Cold Bay SEC.tif'
cp 'Dallas-Ft Worth SEC.tif'                ../../Programs/OpenEagleMaps/Dallas-Ft_Worth_Sectional/'Dallas-Ft Worth SEC.tif'
cp 'Dawson SEC.tif'                         ../../Programs/OpenEagleMaps/Dawson_Sectional/'Dawson SEC.tif'
cp 'Denver SEC.tif'                         ../../Programs/OpenEagleMaps/Denver_Sectional/'Denver SEC.tif'
cp 'Detroit SEC.tif'                        ../../Programs/OpenEagleMaps/Detroit_Sectional/'Detroit SEC.tif'
cp 'Dutch Harbor SEC.tif'                   ../../Programs/OpenEagleMaps/Dutch_Harbor_Sectional/'Dutch Harbor SEC.tif'
cp 'El Paso SEC.tif'                        ../../Programs/OpenEagleMaps/El_Paso_Sectional/'El Paso SEC.tif'
cp 'Fairbanks SEC.tif'                      ../../Programs/OpenEagleMaps/Fairbanks_Sectional/'Fairbanks SEC.tif'
cp 'Grand Canyon Air Tour Operators.tif'    ../../Programs/OpenEagleMaps/Grand_Canyon_Air_Tour_Operators/'Grand Canyon Air Tour Operators.tif'
cp 'Grand Canyon General Aviation.tif'      ../../Programs/OpenEagleMaps/Grand_Canyon_General_Aviation/'Grand Canyon General Aviation.tif'
cp 'Great Falls SEC.tif'                    ../../Programs/OpenEagleMaps/Great_Falls_Sectional/'Great Falls SEC.tif'
cp 'Green Bay SEC.tif'                      ../../Programs/OpenEagleMaps/Green_Bay_Sectional/'Green Bay SEC.tif'
cp 'Halifax SEC.tif'                        ../../Programs/OpenEagleMaps/Halifax_Sectional/'Halifax SEC.tif'
cp 'Hawaiian Islands SEC.tif'               ../../Programs/OpenEagleMaps/Hawaiian_Islands_Sectional/'Hawaiian Islands SEC.tif'
cp 'Honolulu Inset SEC.tif'                 ../../Programs/OpenEagleMaps/Honolulu_Inset_Sectional/'Honolulu Inset SEC.tif'
cp 'Houston SEC.tif'                        ../../Programs/OpenEagleMaps/Houston_Sectional/'Houston SEC.tif'
cp 'Jacksonville SEC.tif'                   ../../Programs/OpenEagleMaps/Jacksonville_Sectional/'Jacksonville SEC.tif'
cp 'Juneau SEC.tif'                         ../../Programs/OpenEagleMaps/Juneau_Sectional/'Juneau SEC.tif'
cp 'Kansas City SEC.tif'                    ../../Programs/OpenEagleMaps/Kansas_City_Sectional/'Kansas City SEC.tif'
cp 'Ketchikan SEC.tif'                      ../../Programs/OpenEagleMaps/Ketchikan_Sectional/'Ketchikan SEC.tif'
cp 'Klamath Falls SEC.tif'                  ../../Programs/OpenEagleMaps/Klamath_Falls_Sectional/'Klamath Falls SEC.tif'
cp 'Kodiak SEC.tif'                         ../../Programs/OpenEagleMaps/Kodiak_Sectional/'Kodiak SEC.tif'
cp 'Lake Huron SEC.tif'                     ../../Programs/OpenEagleMaps/Lake_Huron_Sectional/'Lake Huron SEC.tif'
cp 'Las Vegas SEC.tif'                      ../../Programs/OpenEagleMaps/Las_Vegas_Sectional/'Las Vegas SEC.tif'
cp 'Los Angeles SEC.tif'                    ../../Programs/OpenEagleMaps/Los_Angeles_Sectional/'Los Angeles SEC.tif'
cp 'Mariana Islands Inset SEC.tif'          ../../Programs/OpenEagleMaps/Mariana_Islands_Inset_Sectional/'Mariana Islands Inset SEC.tif'
cp 'McGrath SEC.tif'                        ../../Programs/OpenEagleMaps/McGrath_Sectional/'McGrath SEC.tif'
cp 'Memphis SEC.tif'                        ../../Programs/OpenEagleMaps/Memphis_Sectional/'Memphis SEC.tif'
cp 'Miami SEC.tif'                          ../../Programs/OpenEagleMaps/Miami_Sectional/'Miami SEC.tif'
cp 'Montreal SEC.tif'                       ../../Programs/OpenEagleMaps/Montreal_Sectional/'Montreal SEC.tif'
cp 'New Orleans SEC.tif'                    ../../Programs/OpenEagleMaps/New_Orleans_Sectional/'New Orleans SEC.tif'
cp 'New York SEC.tif'                       ../../Programs/OpenEagleMaps/New_York_Sectional/'New York SEC.tif'
cp 'Nome SEC.tif'                           ../../Programs/OpenEagleMaps/Nome_Sectional/'Nome SEC.tif'
cp 'Omaha SEC.tif'                          ../../Programs/OpenEagleMaps/Omaha_Sectional/'Omaha SEC.tif'
cp 'Phoenix SEC.tif'                        ../../Programs/OpenEagleMaps/Phoenix_Sectional/'Phoenix SEC.tif'
cp 'Point Barrow SEC.tif'                   ../../Programs/OpenEagleMaps/Point_Barrow_Sectional/'Point Barrow SEC.tif'
cp 'Salt Lake City SEC.tif'                 ../../Programs/OpenEagleMaps/Salt_Lake_City_Sectional/'Salt Lake City SEC.tif'
cp 'Samoan Islands Inset SEC.tif'           ../../Programs/OpenEagleMaps/Samoan_Islands_Inset_Sectional/'Samoan Islands Inset SEC.tif'
cp 'San Antonio SEC.tif'                    ../../Programs/OpenEagleMaps/San_Antonio_Sectional/'San Antonio SEC.tif'
cp 'San Francisco SEC.tif'                  ../../Programs/OpenEagleMaps/San_Francisco_Sectional/'San Francisco SEC.tif'
cp 'Seattle SEC.tif'                        ../../Programs/OpenEagleMaps/Seattle_Sectional/'Seattle SEC.tif'
cp 'Seward SEC.tif'                         ../../Programs/OpenEagleMaps/Seward_Sectional/'Seward SEC.tif'
cp 'St Louis SEC.tif'                       ../../Programs/OpenEagleMaps/St_Louis_Sectional/'St Louis SEC.tif'
cp 'Twin Cities SEC.tif'                    ../../Programs/OpenEagleMaps/Twin_Cities_Sectional/'Twin Cities SEC.tif'
cp 'Washington SEC.tif'                     ../../Programs/OpenEagleMaps/Washington_Sectional/'Washington SEC.tif'
cp 'Western Aleutian Islands East SEC.tif'  ../../Programs/OpenEagleMaps/Western_Aleutian_Islands_East_Sectional_WEST/'Western Aleutian Islands East SEC.tif'
cp 'Western Aleutian Islands East SEC.tif'  ../../Programs/OpenEagleMaps/Western_Aleutian_Islands_East_Sectional_EAST/'Western Aleutian Islands East SEC.tif'
cp 'Western Aleutian Islands West SEC.tif'  ../../Programs/OpenEagleMaps/Western_Aleutian_Islands_West_Sectional/'Western Aleutian Islands West SEC.tif'
cp 'Wichita SEC.tif'                        ../../Programs/OpenEagleMaps/Wichita_Sectional/'Wichita SEC.tif'




